[2024-11-26T07:20:27.286+0000] {processor.py:186} INFO - Started process (PID=427) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:20:27.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:20:27.289+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:20:27.289+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:20:27.862+0000] {processor.py:925} INFO - DAG(s) 'extract_weather' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:20:27.982+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:20:27.982+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:20:28.012+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:20:28.011+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather to 2024-11-25 00:00:00+00:00, run_after=2024-11-26 00:00:00+00:00
[2024-11-26T07:20:28.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.827 seconds
[2024-11-26T07:20:58.861+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:20:58.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:20:58.872+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:20:58.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:20:59.879+0000] {processor.py:925} INFO - DAG(s) 'extract_weather' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:20:59.910+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:20:59.910+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:20:59.940+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:20:59.940+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:20:59.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 1.128 seconds
[2024-11-26T07:21:30.708+0000] {processor.py:186} INFO - Started process (PID=440) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:21:30.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:21:30.712+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:21:30.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:21:31.299+0000] {processor.py:925} INFO - DAG(s) 'extract_weather' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:21:31.328+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:21:31.328+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:21:31.352+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:21:31.352+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:21:31.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.674 seconds
[2024-11-26T07:22:01.657+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:01.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:22:01.659+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:22:01.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:02.185+0000] {processor.py:925} INFO - DAG(s) 'extract_weather' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:02.221+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:22:02.220+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:22:02.248+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:22:02.248+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:22:02.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.621 seconds
[2024-11-26T07:22:09.523+0000] {processor.py:186} INFO - Started process (PID=444) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:09.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:22:09.526+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:22:09.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:10.089+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:22:10.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 16, in <module>
    @dag(
     ^^^
NameError: name 'dag' is not defined
[2024-11-26T07:22:10.091+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:10.111+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.593 seconds
[2024-11-26T07:22:40.360+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:40.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:22:40.363+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:22:40.362+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:40.875+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:22:40.869+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 16, in <module>
    @dag(
     ^^^
NameError: name 'dag' is not defined
[2024-11-26T07:22:40.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:40.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.541 seconds
[2024-11-26T07:22:47.515+0000] {processor.py:186} INFO - Started process (PID=448) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:47.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:22:47.521+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:22:47.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:48.123+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:22:48.233+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:22:48.233+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:22:48.256+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:22:48.256+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:22:48.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.773 seconds
[2024-11-26T07:23:18.732+0000] {processor.py:186} INFO - Started process (PID=460) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:23:18.733+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:23:18.736+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:23:18.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:23:19.297+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:23:19.326+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:23:19.326+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:23:19.351+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:23:19.350+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:23:19.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.645 seconds
[2024-11-26T07:23:49.533+0000] {processor.py:186} INFO - Started process (PID=516) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:23:49.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:23:49.538+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:23:49.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:23:50.269+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:23:50.298+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:23:50.298+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:23:50.329+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:23:50.329+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:23:50.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.828 seconds
[2024-11-26T07:24:21.115+0000] {processor.py:186} INFO - Started process (PID=535) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:24:21.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:24:21.118+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:24:21.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:24:21.601+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:24:21.625+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:24:21.624+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:24:21.648+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:24:21.648+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:24:21.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.559 seconds
[2024-11-26T07:24:51.794+0000] {processor.py:186} INFO - Started process (PID=537) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:24:51.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:24:51.797+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:24:51.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:24:52.286+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:24:52.311+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:24:52.310+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:24:52.337+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:24:52.337+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:24:52.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.569 seconds
[2024-11-26T07:25:22.644+0000] {processor.py:186} INFO - Started process (PID=539) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:25:22.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:25:22.647+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:25:22.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:25:23.129+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:25:23.156+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:25:23.155+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:25:23.179+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:25:23.179+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:25:23.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.563 seconds
[2024-11-26T07:25:53.342+0000] {processor.py:186} INFO - Started process (PID=541) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:25:53.344+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:25:53.345+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:25:53.345+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:25:53.827+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:25:53.852+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:25:53.852+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:25:53.875+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:25:53.875+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:25:53.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.555 seconds
[2024-11-26T07:26:24.116+0000] {processor.py:186} INFO - Started process (PID=543) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:26:24.117+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:26:24.118+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:26:24.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:26:24.591+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:26:24.614+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:26:24.613+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:26:24.637+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:26:24.637+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:26:24.657+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.548 seconds
[2024-11-26T07:26:54.774+0000] {processor.py:186} INFO - Started process (PID=545) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:26:54.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:26:54.777+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:26:54.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:26:55.231+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:26:55.256+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:26:55.255+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:26:55.277+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:26:55.277+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:26:55.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.529 seconds
[2024-11-26T07:27:25.529+0000] {processor.py:186} INFO - Started process (PID=547) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:27:25.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:27:25.533+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:27:25.533+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:27:26.002+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:27:26.030+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:27:26.029+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:27:26.053+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:27:26.053+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:27:26.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.549 seconds
[2024-11-26T07:27:56.420+0000] {processor.py:186} INFO - Started process (PID=557) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:27:56.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:27:56.423+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:27:56.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:27:56.997+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:27:56.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:27:57.000+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:27:57.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:27:57.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.612 seconds
[2024-11-26T07:28:27.155+0000] {processor.py:186} INFO - Started process (PID=608) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:28:27.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:28:27.157+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:28:27.157+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:28:27.686+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:28:27.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:28:27.688+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:28:27.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:28:27.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.559 seconds
[2024-11-26T07:28:56.009+0000] {processor.py:186} INFO - Started process (PID=616) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:28:56.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:28:56.012+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:28:56.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:28:56.501+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:28:56.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 31, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got an unexpected keyword argument 'op_kwargs'
[2024-11-26T07:28:56.502+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:28:56.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:28:56.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.519 seconds
[2024-11-26T07:29:11.690+0000] {processor.py:186} INFO - Started process (PID=618) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:29:11.691+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:29:11.693+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:29:11.693+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:29:12.282+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:29:12.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 31, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got an unexpected keyword argument 'op_kwargs'
[2024-11-26T07:29:12.286+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:29:12.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:29:12.311+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.627 seconds
[2024-11-26T07:29:43.044+0000] {processor.py:186} INFO - Started process (PID=620) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:29:43.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:29:43.047+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:29:43.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:29:43.577+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:29:43.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 31, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got an unexpected keyword argument 'op_kwargs'
[2024-11-26T07:29:43.580+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:29:43.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:29:43.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.565 seconds
[2024-11-26T07:30:13.684+0000] {processor.py:186} INFO - Started process (PID=622) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:30:13.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:30:13.688+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:30:13.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:30:14.198+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:30:14.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 31, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got an unexpected keyword argument 'op_kwargs'
[2024-11-26T07:30:14.201+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:30:14.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:30:14.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.542 seconds
[2024-11-26T07:30:44.578+0000] {processor.py:186} INFO - Started process (PID=624) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:30:44.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:30:44.581+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:30:44.581+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:30:45.107+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:30:45.101+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 31, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got an unexpected keyword argument 'op_kwargs'
[2024-11-26T07:30:45.109+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:30:45.109+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:30:45.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.557 seconds
[2024-11-26T07:31:15.254+0000] {processor.py:186} INFO - Started process (PID=626) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:31:15.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:31:15.257+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:31:15.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:31:15.712+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:31:15.707+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 31, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got an unexpected keyword argument 'op_kwargs'
[2024-11-26T07:31:15.714+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:31:15.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:31:15.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.486 seconds
[2024-11-26T07:31:32.724+0000] {processor.py:186} INFO - Started process (PID=628) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:31:32.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:31:32.748+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:31:32.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:31:33.351+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:31:33.346+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:31:33.353+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:31:33.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:31:33.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.654 seconds
[2024-11-26T07:32:03.562+0000] {processor.py:186} INFO - Started process (PID=630) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:32:03.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:32:03.566+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:32:03.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:32:04.057+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:32:04.051+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:32:04.059+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:32:04.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:32:04.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.522 seconds
[2024-11-26T07:32:34.336+0000] {processor.py:186} INFO - Started process (PID=632) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:32:34.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:32:34.339+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:32:34.338+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:32:34.936+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:32:34.928+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:32:34.938+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:32:34.938+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:32:34.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.629 seconds
[2024-11-26T07:33:05.080+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:33:05.081+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:33:05.083+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:33:05.082+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:33:05.548+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:33:05.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:33:05.550+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:33:05.551+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:33:05.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.498 seconds
[2024-11-26T07:33:35.946+0000] {processor.py:186} INFO - Started process (PID=636) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:33:35.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:33:35.949+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:33:35.948+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:33:36.416+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:33:36.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:33:36.418+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:33:36.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:33:36.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.498 seconds
[2024-11-26T07:34:06.646+0000] {processor.py:186} INFO - Started process (PID=638) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:34:06.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:34:06.649+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:34:06.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:34:07.154+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:34:07.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:34:07.156+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:34:07.156+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:34:07.175+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.535 seconds
[2024-11-26T07:34:37.381+0000] {processor.py:186} INFO - Started process (PID=640) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:34:37.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:34:37.388+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:34:37.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:34:37.982+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:34:38.096+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:34:38.095+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:34:38.118+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:34:38.117+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:34:38.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.771 seconds
[2024-11-26T07:35:08.298+0000] {processor.py:186} INFO - Started process (PID=694) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:35:08.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:35:08.301+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:35:08.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:35:08.958+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:35:08.983+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:35:08.983+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:35:09.007+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:35:09.007+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:35:09.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.741 seconds
[2024-11-26T07:35:39.226+0000] {processor.py:186} INFO - Started process (PID=742) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:35:39.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:35:39.229+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:35:39.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:35:39.792+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:35:39.821+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:35:39.820+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:35:39.850+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:35:39.850+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:35:39.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.652 seconds
[2024-11-26T07:36:10.144+0000] {processor.py:186} INFO - Started process (PID=798) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:36:10.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:36:10.148+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:36:10.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:36:10.836+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:36:10.865+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:36:10.864+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:36:10.890+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:36:10.890+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:36:10.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.773 seconds
[2024-11-26T07:36:41.249+0000] {processor.py:186} INFO - Started process (PID=808) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:36:41.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:36:41.252+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:36:41.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:36:41.732+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:36:41.756+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:36:41.756+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:36:41.780+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:36:41.779+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:36:41.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.558 seconds
[2024-11-26T07:37:12.603+0000] {processor.py:186} INFO - Started process (PID=810) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:37:12.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:37:12.606+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:37:12.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:37:13.147+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:37:13.174+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:37:13.173+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:37:13.201+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:37:13.201+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:37:13.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.627 seconds
[2024-11-26T07:37:43.270+0000] {processor.py:186} INFO - Started process (PID=812) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:37:43.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:37:43.273+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:37:43.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:37:43.769+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:37:43.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:37:43.770+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:37:43.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:37:43.790+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.525 seconds
[2024-11-26T07:38:14.119+0000] {processor.py:186} INFO - Started process (PID=814) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:38:14.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:38:14.122+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:38:14.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:38:14.624+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:38:14.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:38:14.626+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:38:14.626+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:38:14.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.531 seconds
[2024-11-26T07:38:44.848+0000] {processor.py:186} INFO - Started process (PID=816) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:38:44.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:38:44.850+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:38:44.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:38:45.341+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:38:45.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:38:45.343+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:38:45.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:38:45.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.523 seconds
[2024-11-26T07:39:15.725+0000] {processor.py:186} INFO - Started process (PID=818) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:39:15.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:39:15.727+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:39:15.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:39:16.216+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:39:16.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:39:16.218+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:39:16.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:39:16.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.517 seconds
[2024-11-26T07:39:46.396+0000] {processor.py:186} INFO - Started process (PID=820) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:39:46.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:39:46.399+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:39:46.398+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:39:46.875+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:39:46.869+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:39:46.877+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:39:46.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:39:46.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.505 seconds
[2024-11-26T07:40:17.141+0000] {processor.py:186} INFO - Started process (PID=822) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:40:17.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:40:17.145+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:40:17.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:40:17.620+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:40:17.612+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:40:17.622+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:40:17.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:40:17.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.506 seconds
[2024-11-26T07:40:47.789+0000] {processor.py:186} INFO - Started process (PID=824) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:40:47.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:40:47.791+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:40:47.791+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:40:48.300+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:40:48.287+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extract_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extract_weather.py", line 32, in <module>
    dag = extract_weather_dag()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/extract_weather.py", line 23, in extract_weather_dag
    ).expand(
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 181, in expand
    validate_mapping_kwargs(self.operator_class, "expand", mapped_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py", line 123, in validate_mapping_kwargs
    raise TypeError(f"{op.__name__}.{func}() got {error}")
TypeError: WeatherToCSVOperator.expand() got unexpected keyword arguments 'city', 'file_path'
[2024-11-26T07:40:48.302+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/mappedoperator.py:176 UserWarning: Task 'extract_data' was never mapped!
[2024-11-26T07:40:48.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:40:48.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.555 seconds
[2024-11-26T07:41:12.375+0000] {processor.py:186} INFO - Started process (PID=826) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:41:12.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:41:12.377+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:41:12.377+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:41:12.879+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:41:12.987+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:41:12.987+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:41:13.007+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:41:13.007+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:41:13.042+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.673 seconds
[2024-11-26T07:41:21.844+0000] {processor.py:186} INFO - Started process (PID=828) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:41:21.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:41:21.847+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:41:21.846+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:41:22.409+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:41:22.421+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:41:22.421+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:41:22.446+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:41:22.445+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:41:22.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.634 seconds
[2024-11-26T07:41:52.902+0000] {processor.py:186} INFO - Started process (PID=857) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:41:52.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:41:52.906+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:41:52.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:41:53.784+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:41:53.951+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:41:53.950+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:41:53.976+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:41:53.976+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:41:54.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 1.103 seconds
[2024-11-26T07:42:24.686+0000] {processor.py:186} INFO - Started process (PID=868) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:42:24.687+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:42:24.688+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:42:24.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:42:25.239+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:42:25.267+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:42:25.267+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:42:25.294+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:42:25.293+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:42:25.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.637 seconds
[2024-11-26T07:42:55.407+0000] {processor.py:186} INFO - Started process (PID=888) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:42:55.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:42:55.410+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:42:55.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:42:55.899+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:42:55.925+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:42:55.924+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:42:55.946+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:42:55.946+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:42:55.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.575 seconds
[2024-11-26T07:43:26.262+0000] {processor.py:186} INFO - Started process (PID=890) to work on /opt/airflow/dags/extract_weather.py
[2024-11-26T07:43:26.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extract_weather.py for tasks to queue
[2024-11-26T07:43:26.265+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:43:26.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:43:26.744+0000] {processor.py:925} INFO - DAG(s) 'extract_weather_dag' retrieved from /opt/airflow/dags/extract_weather.py
[2024-11-26T07:43:26.769+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:43:26.768+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-11-26T07:43:26.795+0000] {logging_mixin.py:190} INFO - [2024-11-26T07:43:26.794+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_weather_dag to 2024-11-26 00:00:00+00:00, run_after=2024-11-27 00:00:00+00:00
[2024-11-26T07:43:26.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extract_weather.py took 0.561 seconds
